#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py makemigrations --no-input
python manage.py migrate --no-input
python manage.py collectstatic --no-input
python manage.py schedule_unsent_notifications
python manage.py reschedule_recurring_events

NUM_WORKERS=${GUNICORN_WORKERS:-3}

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:8000 --chdir=/app --workers $NUM_WORKERS
