# Generated by Django 4.2 on 2025-04-30 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_method', models.CharField(choices=[('email', 'Email'), ('tg', 'Telegram')], default='email', max_length=10, verbose_name='Notification Method')),
                ('notification_datetime', models.DateTimeField(verbose_name='Notification Datetime')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Celery Task ID')),
                ('is_sent', models.BooleanField(blank=True, default=False, verbose_name='Is Sent')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-notification_datetime'],
            },
        ),
    ]
