# Generated by Django 4.2 on 2025-05-02 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCard',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Full Organization Name')),
                ('edrpou_code', models.CharField(max_length=8, verbose_name='EDRPOU Code')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Region')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('full_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Applicant Full Name')),
                ('id_number', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='IPN or series/number of document')),
                ('keyword_phrase', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Keyword Phrase')),
                ('voice_phrase', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Voice Phrase')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region=None, verbose_name='Phone Number')),
                ('electronic_seal_name', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Electronic Seal Name')),
                ('electronic_seal_keyword_phrase', encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='Electronic Seal Keyword Phrase')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Registration Card',
                'verbose_name_plural': 'Registration Cards',
            },
        ),
    ]
