# Generated by Django 4.2 on 2025-07-27 15:19

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationcard',
            options={'ordering': ['issue_date'], 'verbose_name': 'Registration Card', 'verbose_name_plural': 'Registration Cards'},
        ),
        migrations.AddField(
            model_name='registrationcard',
            name='expiration_date',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AddField(
            model_name='registrationcard',
            name='issue_date',
            field=encrypted_model_fields.fields.EncryptedDateField(blank=True, null=True, verbose_name='Signing Date'),
        ),
    ]
