# Generated by Django 4.2 on 2025-05-10 12:50

import apps.common.uploads
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.upload_event_image, validators=[apps.common.validators.image_validator], verbose_name='Image'),
        ),
    ]
