# Generated by Django 4.2 on 2025-05-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
    ]
