# Generated by Django 4.2 on 2025-06-01 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurringevent',
            name='last_occurrence',
        ),
        migrations.RemoveField(
            model_name='recurringevent',
            name='next_occurrence',
        ),
        migrations.AddField(
            model_name='recurringevent',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
