from django.urls import path
from .views import (
    TeamListAPIView,
    TeamCreateAPIView,
    TeamUpdateAPIView,
    TeamDetailAPIView,
    TeamDeleteAPIView,
    RemoveTeamMemberView,
    TeamLeaveAPIView,
    InvitationListCreateAPIView,
    InvitationListAPIView,
    InvitationDetailAPIView,
    InvitationRespondAPIView,
    InvitationDeleteAPIView,
    TeamMembersListAPIView,
    TeamEventsListAPIView,
    TeamInvitationsListAPIView,
)

urlpatterns = [
    path('', TeamListAPIView.as_view(), name='team-list'),
    path('create/', TeamCreateAPIView.as_view(), name='team-create'),
    path('<uuid:id>/', TeamDetailAPIView.as_view(), name='team-detail'),
    path('<uuid:id>/update/', TeamUpdateAPIView.as_view(), name='team-update'),
    path('<uuid:id>/delete/', TeamDeleteAPIView.as_view(), name='team-delete'),
    path('<uuid:id>/leave/', TeamLeaveAPIView.as_view(), name='team-leave'),
    path('<uuid:team_id>/members/', TeamMembersListAPIView.as_view(), name='team-members'),
    path('<uuid:team_id>/events/', TeamEventsListAPIView.as_view(), name='team-events'),
    path('<uuid:team_id>/invitations/', TeamInvitationsListAPIView.as_view(), name='team-invitations'),
    path('<uuid:team_id>/remove-member/<uuid:user_id>/', RemoveTeamMemberView.as_view(), name='team-remove-member'),
    path('invitations/', InvitationListAPIView.as_view(), name='invitation-list'),
    path('invitations/create/', InvitationListCreateAPIView.as_view(), name='invitation-create'),
    path('invitations/<uuid:id>/', InvitationDetailAPIView.as_view(), name='invitation-detail'),
    path('invitations/<uuid:id>/respond/', InvitationRespondAPIView.as_view(), name='invitation-respond'),
    path('invitations/<uuid:id>/delete/', InvitationDeleteAPIView.as_view(), name='invitation-delete'),
]
