# Generated by Django 4.2 on 2025-04-27 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('position', models.CharField(max_length=250, verbose_name='Position')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], default='o', max_length=10, verbose_name='Gender')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, unique=True, verbose_name='Phone Number')),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram Username')),
                ('telegram_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, unique=True, verbose_name='Telegram Phone Number')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='units.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['telegram_username'], name='profiles_pr_telegra_f53e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['telegram_phone_number'], name='profiles_pr_telegra_9bd0be_idx'),
        ),
    ]
