# Generated by Django 4.2 on 2025-04-26 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['telegram_username'], name='profiles_pr_telegra_f53e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['telegram_phone_number'], name='profiles_pr_telegra_9bd0be_idx'),
        ),
    ]
