# Generated by Django 4.2 on 2025-05-05 12:18

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_phone_number_alter_profile_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramData',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('telegram_username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Telegram Username')),
                ('telegram_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, unique=True, verbose_name='Telegram Phone Number')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram User Id')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram Chat Id')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
            ],
            options={
                'verbose_name': 'Telegram Data',
                'verbose_name_plural': 'Telegram Data',
            },
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_telegra_f53e7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='profile',
            name='profiles_pr_telegra_9bd0be_idx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='telegramdata',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram', to='profiles.profile'),
        ),
        migrations.AddIndex(
            model_name='telegramdata',
            index=models.Index(fields=['telegram_username'], name='profiles_te_telegra_8d4e41_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramdata',
            index=models.Index(fields=['telegram_phone_number'], name='profiles_te_telegra_73ac29_idx'),
        ),
    ]
