# Generated by Django 4.2 on 2025-05-10 12:53

import apps.common.uploads
import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_telegramdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.common.uploads.upload_avatar, validators=[apps.common.validators.image_validator], verbose_name='Avatar'),
        ),
    ]
