# Generated by Django 4.2 on 2025-05-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['position'], name='profiles_pr_positio_4a4754_idx'),
        ),
    ]
