# Generated by Django 4.2 on 2025-06-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_gender_remove_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telegramdata',
            name='profiles_te_telegra_8d4e41_idx',
        ),
        migrations.RemoveIndex(
            model_name='telegramdata',
            name='profiles_te_telegra_73ac29_idx',
        ),
        migrations.RemoveField(
            model_name='telegramdata',
            name='telegram_chat_id',
        ),
        migrations.RemoveField(
            model_name='telegramdata',
            name='telegram_phone_number',
        ),
        migrations.AddField(
            model_name='telegramdata',
            name='telegram_first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Telegram First Name'),
        ),
        migrations.AddField(
            model_name='telegramdata',
            name='telegram_last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Telegram Last Name'),
        ),
        migrations.AlterField(
            model_name='telegramdata',
            name='telegram_user_id',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='Telegram User Id'),
        ),
        migrations.AlterField(
            model_name='telegramdata',
            name='telegram_username',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Telegram Username'),
        ),
    ]
