# Generated by Django 4.2 on 2025-05-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_abbreviation',
            field=models.CharField(max_length=20, verbose_name='Department Аbbreviation'),
        ),
    ]
